name: CI

on:
  push:
    paths:
      - java-r5rcore/**
      - r-package/**
      - .github/workflows/**

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: R-CMD-check ${{ matrix.config.os }} (R ${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-22.04, r: 'devel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/jammy/latest"}
          - {os: ubuntu-22.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/jammy/latest"}
          - {os: ubuntu-22.04, r: 'oldrel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/jammy/latest"}

    env:
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v2

      # Java setup for macOS (using the proper arm64 architecture)
      - name: Java setup (macOS)
        if: runner.os == 'macOS'
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
          architecture: arm64

      # Java setup for non-macOS runners
      - name: Java setup (non-macOS)
        if: runner.os != 'macOS'
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
          working-directory: r-package

      - uses: r-lib/actions/check-r-package@v2
        with:
          working-directory: r-package

  R-CMD-check-CRAN:
    runs-on: ${{ matrix.config.os }}

    name: R-CMD-check-CRAN

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-22.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/jammy/latest"}

    env:
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
          working-directory: r-package

      - uses: r-lib/actions/check-r-package@v2
        with:
          working-directory: r-package
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
          NOT_CRAN: false

  test-coverage:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-r@v2

      - name: Java setup
        uses: actions/setup-java@v1
        with:
          java-version: '21'
          java-package: jdk

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr, any::xml2
          needs: coverage
          working-directory: r-package

      - name: Test coverage
        run: |
          cov <- covr::package_coverage(
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
          )
          covr::to_cobertura(cov)
        shell: Rscript {0}
        working-directory: r-package

      - uses: codecov/codecov-action@v4
        with:
          # Fail if error if not on PR, or if on PR and token is given
          fail_ci_if_error: ${{ github.event_name != 'pull_request' || secrets.CODECOV_TOKEN }}
          file: ./cobertura.xml
          plugin: noop
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}
          working-directory: r-package